//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilBor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adses
    {
        public int ID { get; set; }
        public Nullable<int> Operation_Id { get; set; }
        public Nullable<int> Property_Id { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Area_Id { get; set; }
        public Nullable<int> Zone_Id { get; set; }
        public string Address { get; set; }
        public Nullable<int> Build_Id { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<int> Classification_Id { get; set; }
        public Nullable<int> Metro_Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Contacts_Id { get; set; }
        public Nullable<int> PriceType_Id { get; set; }
        public string ShortText { get; set; }
        public Nullable<int> CountRooms { get; set; }
        public Nullable<int> SquarePlace { get; set; }
        public string LivePlace { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> All_Floor { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Images { get; set; }
        public string Title { get; set; }
        public Nullable<int> Furniture { get; set; }
        public Nullable<int> Comissions { get; set; }
        public Nullable<int> Top_Ads { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Assignment_Id { get; set; }
        public Nullable<int> Accept_Rejection { get; set; }
        public string About_Mistake { get; set; }
        public Nullable<int> Price_Real { get; set; }
    }
}
