//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilBor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments
    {
        public int ID { get; set; }
        public string assignmentName { get; set; }
        public string assignmentNameRu { get; set; }
    }
}
