//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilBor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        public int ID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> PriceType { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> MoneyType { get; set; }
        public Nullable<int> Contact { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Face { get; set; }
        public string Text { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Picture3 { get; set; }
        public string Picture4 { get; set; }
        public string Picture5 { get; set; }
        public string Picture6 { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
