//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int Id { get; set; }
        public string Person_Name { get; set; }
        public string Person_Address { get; set; }
        public Nullable<int> Summary { get; set; }
        public string PhonoNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Area_Id { get; set; }
        public Nullable<int> Event_Id { get; set; }
        public Nullable<int> Exper_Id { get; set; }
        public Nullable<int> Term_Id { get; set; }
        public Nullable<int> Type_UserId { get; set; }
        public Nullable<int> Born { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<int> Transport_Id { get; set; }
    }
}
