//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qabulxona.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public long AnswerId { get; set; }
        public Nullable<long> RequestId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AnswerText { get; set; }
        public string AnswerFile { get; set; }
        public Nullable<int> AnswerStatus { get; set; }
        public string VisaFile { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<System.DateTime> DaysToSolve { get; set; }
        public string AnswerComment { get; set; }
        public Nullable<System.DateTime> UserReadDate { get; set; }
        public Nullable<System.DateTime> UserAnswDate { get; set; }
        public string ispol { get; set; }
        public Nullable<System.DateTime> DaysToSolveForIspol { get; set; }
    }
}
