//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qabulxona.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        public int AreaId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string AreaNameUzk { get; set; }
        public string AreaNameRu { get; set; }
    }
}
