//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qabulxona.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class qabulxonaEntities1 : DbContext
    {
        public qabulxonaEntities1()
            : base("name=qabulxonaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<RequestStatuses> RequestStatuses { get; set; }
        public virtual DbSet<RequestSubjectTypes> RequestSubjectTypes { get; set; }
        public virtual DbSet<Sexs> Sexs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        [DbFunction("qabulxonaEntities1", "CheckLogin")]
        public virtual IQueryable<CheckLogin_Result> CheckLogin(string login, string password)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CheckLogin_Result>("[qabulxonaEntities1].[CheckLogin](@Login, @Password)", loginParameter, passwordParameter);
        }
    
        [DbFunction("qabulxonaEntities1", "CloseCompleteRequests")]
        public virtual IQueryable<CloseCompleteRequests_Result> CloseCompleteRequests(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CloseCompleteRequests_Result>("[qabulxonaEntities1].[CloseCompleteRequests](@UserId)", userIdParameter);
        }
    
        [DbFunction("qabulxonaEntities1", "CloseRequests")]
        public virtual IQueryable<CloseRequests_Result> CloseRequests(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CloseRequests_Result>("[qabulxonaEntities1].[CloseRequests](@UserId)", userIdParameter);
        }
    
        [DbFunction("qabulxonaEntities1", "CloseRequestsForOthers")]
        public virtual IQueryable<CloseRequestsForOthers_Result> CloseRequestsForOthers(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CloseRequestsForOthers_Result>("[qabulxonaEntities1].[CloseRequestsForOthers](@UserId)", userIdParameter);
        }
    
        [DbFunction("qabulxonaEntities1", "CompleteRequests")]
        public virtual IQueryable<CompleteRequests_Result> CompleteRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CompleteRequests_Result>("[qabulxonaEntities1].[CompleteRequests]()");
        }
    
        [DbFunction("qabulxonaEntities1", "expired1_3")]
        public virtual IQueryable<expired1_3_Result> expired1_3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<expired1_3_Result>("[qabulxonaEntities1].[expired1_3]()");
        }
    
        [DbFunction("qabulxonaEntities1", "expired1_3ForIspol")]
        public virtual IQueryable<expired1_3ForIspol_Result> expired1_3ForIspol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<expired1_3ForIspol_Result>("[qabulxonaEntities1].[expired1_3ForIspol]()");
        }
    
        [DbFunction("qabulxonaEntities1", "expired10_")]
        public virtual IQueryable<expired10__Result> expired10_()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<expired10__Result>("[qabulxonaEntities1].[expired10_]()");
        }
    
        [DbFunction("qabulxonaEntities1", "expired10_ForIspol")]
        public virtual IQueryable<expired10_ForIspol_Result> expired10_ForIspol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<expired10_ForIspol_Result>("[qabulxonaEntities1].[expired10_ForIspol]()");
        }
    
        [DbFunction("qabulxonaEntities1", "expired3_5")]
        public virtual IQueryable<expired3_5_Result> expired3_5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<expired3_5_Result>("[qabulxonaEntities1].[expired3_5]()");
        }
    
        [DbFunction("qabulxonaEntities1", "expired3_5ForIspol")]
        public virtual IQueryable<expired3_5ForIspol_Result> expired3_5ForIspol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<expired3_5ForIspol_Result>("[qabulxonaEntities1].[expired3_5ForIspol]()");
        }
    
        [DbFunction("qabulxonaEntities1", "expired5_10")]
        public virtual IQueryable<expired5_10_Result> expired5_10()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<expired5_10_Result>("[qabulxonaEntities1].[expired5_10]()");
        }
    
        [DbFunction("qabulxonaEntities1", "expired5_10ForIspol")]
        public virtual IQueryable<expired5_10ForIspol_Result> expired5_10ForIspol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<expired5_10ForIspol_Result>("[qabulxonaEntities1].[expired5_10ForIspol]()");
        }
    
        [DbFunction("qabulxonaEntities1", "NewRequests")]
        public virtual IQueryable<NewRequests_Result> NewRequests(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<NewRequests_Result>("[qabulxonaEntities1].[NewRequests](@UserId)", userIdParameter);
        }
    
        [DbFunction("qabulxonaEntities1", "OpenRequests")]
        public virtual IQueryable<OpenRequests_Result> OpenRequests(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<OpenRequests_Result>("[qabulxonaEntities1].[OpenRequests](@UserId)", userIdParameter);
        }
    
        [DbFunction("qabulxonaEntities1", "OpenRetweetRequests")]
        public virtual IQueryable<OpenRetweetRequests_Result> OpenRetweetRequests(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<OpenRetweetRequests_Result>("[qabulxonaEntities1].[OpenRetweetRequests](@UserId)", userIdParameter);
        }
    
        [DbFunction("qabulxonaEntities1", "ReqStatistic")]
        public virtual IQueryable<ReqStatistic_Result> ReqStatistic()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ReqStatistic_Result>("[qabulxonaEntities1].[ReqStatistic]()");
        }
    
        [DbFunction("qabulxonaEntities1", "ReqStatUser")]
        public virtual IQueryable<ReqStatUser_Result> ReqStatUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ReqStatUser_Result>("[qabulxonaEntities1].[ReqStatUser](@UserId)", userIdParameter);
        }
    
        [DbFunction("qabulxonaEntities1", "RetweetRequests")]
        public virtual IQueryable<RetweetRequests_Result> RetweetRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RetweetRequests_Result>("[qabulxonaEntities1].[RetweetRequests]()");
        }
    
        [DbFunction("qabulxonaEntities1", "Soon1")]
        public virtual IQueryable<Soon1_Result> Soon1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Soon1_Result>("[qabulxonaEntities1].[Soon1]()");
        }
    
        [DbFunction("qabulxonaEntities1", "Soon1_3")]
        public virtual IQueryable<Soon1_3_Result> Soon1_3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Soon1_3_Result>("[qabulxonaEntities1].[Soon1_3]()");
        }
    
        [DbFunction("qabulxonaEntities1", "Soon1ForIspol")]
        public virtual IQueryable<Soon1ForIspol_Result> Soon1ForIspol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Soon1ForIspol_Result>("[qabulxonaEntities1].[Soon1ForIspol]()");
        }
    
        [DbFunction("qabulxonaEntities1", "Soon2ForIspol")]
        public virtual IQueryable<Soon2ForIspol_Result> Soon2ForIspol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Soon2ForIspol_Result>("[qabulxonaEntities1].[Soon2ForIspol]()");
        }
    
        [DbFunction("qabulxonaEntities1", "Soon3ForIspol")]
        public virtual IQueryable<Soon3ForIspol_Result> Soon3ForIspol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Soon3ForIspol_Result>("[qabulxonaEntities1].[Soon3ForIspol]()");
        }
    
        [DbFunction("qabulxonaEntities1", "Soon4_7")]
        public virtual IQueryable<Soon4_7_Result> Soon4_7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Soon4_7_Result>("[qabulxonaEntities1].[Soon4_7]()");
        }
    
        [DbFunction("qabulxonaEntities1", "TotalExpired")]
        public virtual IQueryable<TotalExpired_Result> TotalExpired()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TotalExpired_Result>("[qabulxonaEntities1].[TotalExpired]()");
        }
    
        [DbFunction("qabulxonaEntities1", "TotalExpiredForIspol")]
        public virtual IQueryable<TotalExpiredForIspol_Result> TotalExpiredForIspol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TotalExpiredForIspol_Result>("[qabulxonaEntities1].[TotalExpiredForIspol]()");
        }
    }
}
