//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qabulxona.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatuses
    {
        public int StatusId { get; set; }
        public string StatusNameUzk { get; set; }
        public string StatusNameRu { get; set; }
    }
}
