//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qabulxona.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestSubjectTypes
    {
        public int RequestSubjectTypeID { get; set; }
        public string RequestSubjectNameUz { get; set; }
        public string RequestSubjectNameRu { get; set; }
    }
}
