//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qabulxona.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sexs
    {
        public int SexId { get; set; }
        public string SexNameUzk { get; set; }
        public string SexNameRu { get; set; }
    }
}
